server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/patients_details_data
    username: postgres
  jpa:
    properties:
      hibernate:
        default_schema: patients
    hibernate:
      ddl-auto: create
    show-sql: true
welcome:
  message: Welcome to patient demographics data database!!
